### ISSUE TITLE
Question: Running script inside ECS task

### ISSUE THREAD

**Issue by trallnag** [signal-ai/prometheus-ecs-sd#10]
I want to run the script inside an ECS task (with the correct task role and policies) but it seems like the script/boto3 is oblivious to the credentials provided by the env variable `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`.

When I run the script as-is in a vanilla container with all necessary packages installed I get a `missing region` error. When I configure the region via an environment variable, I get a `security token invalid` error. When I get the credentials manually and put them all into env variables including the security token, I can communicate with the AWS API, but the script still does not work.

Do I have to manage the authentication myself in this case? Maybe forking the script and adding code that gets the credentials from  `169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` and configure the boto3 session?

Thanks in advance

**Comment by trallnag** [comment]
Okay I got it to work. Instead of `boto3.client('ecs')` I have to create a session first and then use it to get the client:

```python
import boto3
session = boto3.session.Session()
print(session.get_credentials().get_frozen_credentials())
ecs_client = session.client("ecs")
```

Like that the script will work running within an ECS task.

But what I'm asking myself now: **Will the script fail once the temporary credentials run out?** So I guess I have to wrap everything in a big try/catch and restart the script once that happens.

**Comment by barbasa** [comment]
Hi @trallnag,
any chance you can post the full patch you used to make it work?

I am facing the same issue but I didn't manage yet to make it work.

Thanks

**Comment by barbasa** [comment]
@trallnag I was facing your same issue and I have managed to make it work by adding the policy described in the [documentation](https://github.com/signal-ai/prometheus-ecs-sd#ec2-iam-policy) with the addition of this action: `ec2:DescribeInstances`.

I can share the cloudformation I am using if it is of any help.

**Comment by trallnag** [comment]
@barbasa Yes, that would be great. I'm sure someone will come across this issue and appreciate the example
