### ISSUE TITLE
Client Error? Where should I add the IAM role to allow the client to access stats? 

### ISSUE THREAD

**Issue by HIMADRI518** [signal-ai/prometheus-ecs-sd#5]
[ec2-user@ip-10-6-22-221 prometheus-ecs-sd]$ python discoverecs.py --directory /opt/prometheus-ecs
Starting. Directory: /opt/prometheus-ecs. Interval: 60s.
Traceback (most recent call last):
  File "discoverecs.py", line 410, in <module>
    main()
  File "discoverecs.py", line 407, in main
    Main(args.directory, float(args.interval)).loop()
  File "discoverecs.py", line 398, in loop
    self.discover_tasks()
  File "discoverecs.py", line 359, in discover_tasks
    targets = self.get_targets()
  File "discoverecs.py", line 353, in get_targets
    infos = self.discoverer.get_infos()
  File "discoverecs.py", line 227, in get_infos
    for clusters in clusters_pages:
  File "/home/ec2-user/.local/lib/python2.7/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the ListClusters operation: The security token included in the request is invalid.

**Comment by fredsig** [comment]
Hi HIMADRI518, are you running discoverecs.py from an ec2 instance? If that is the case, you'll need to attach an IAM instance profile (with an attached role) to your ec2 instance so discoverecs.py can pick it up through the boto3 library. Check our README.md file (https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html) for the kind of policy you will need to attach to your IAM role. This also might help:

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html

**Comment by HIMADRI518** [comment]
Thanks for responding. I am aware about attaching an instance profile with relevant role but I am still seeing the same error. That's why I would really appreciate if you can guide with what specfic policy to attach that grants access to applications running on ec2 instances ?

**Comment by HIMADRI518** [comment]
Here is a list of policies I have in my role,  
AmazonEC2RoleforSSM
 AmazonEC2ContainerRegistryFullAccess
 AmazonSSMFullAccess
 AmazonEC2ContainerServiceFullAccess
 AmazonECSTaskExecutionRolePolicy
 AmazonEC2ContainerServiceforEC2Role
 AmazonEC2ContainerServiceRole
 AmazonSSMReadOnlyAccess

**Comment by HIMADRI518** [comment]
Looks like I had to make some changes on my instance credentials. Running into this error now, 
```
    self.write_jobs(jobs)
  File "discoverecs.py", line 347, in write_jobs
    with open(tmp_file_name, 'w') as f:
IOError: [Errno 2] No such file or directory: '/opt/prometheus-ecs/5m-tasks.json.tmp'
```

**Comment by fredsig** [comment]
Sorry for the delay. From the error, it seems the /opt/prometheus-ecs doesn't exist. You will have to create it first:

`mkdir /opt/prometheus-ecs`

and run the tool again. You can of course, choose a different directory. Make sure both the tool and Prometheus have the permissions to access.

**Comment by fredsig** [comment]
Closing this for now.
